### ISSUE TITLE
BLID and Password

### ISSUE THREAD

**Issue by MrMxyzptlk** [umesan/homebridge-roomba#1]
How do I find the BLID and password?

**Comment by umesan** [comment]
I wrote a procedure to [README.md](https://github.com/umesan/homebridge-roomba/blob/master/README.md).

**Comment by MrMxyzptlk** [comment]
Thank you!

I was able to follow your procedure perfectly.

**Comment by tomto147** [comment]
Unfortunately I am not able to find my BLID and password. I have installed Charles, configured proxy, I can see i robot.axeda.com communication, but I am not able to find the needed information in Contents RAW format. Can you advise me and help? Thanks

**Comment by koalazak** [comment]
Hi @tomto147, try the [dorita980](https://github.com/koalazak/dorita980#how-to-get-your-usernameblid-and-password) script for that

**Comment by tomto147** [comment]
I have tryied it as well. I got no response from Roomba after pressing home button for over 2 sec. IP address was ok. After few minutes the script returned error ;-(

**Comment by koalazak** [comment]
what firmware version you have?

**Comment by tomto147** [comment]
Firmware of what? Roomba?

**Comment by koalazak** [comment]
yes.
To check the robot's firmware, open the iRobot HOME App and select More ➔ Settings ➔ About [Robot Name].

**Comment by tomto147** [comment]
1.4.7

**Comment by koalazak** [comment]
Are you sure you have 980 model? cos firm 1.4.7 does not exist in roomba 980:
http://homesupport.irobot.com/app/answers/detail/a_id/529/~/roomba-900-software-release-notes

**Comment by tomto147** [comment]
Quite sure. But I will double check tomorrow

**Comment by tomto147** [comment]
Hmmm don't know how but now the firmware version is 1.6.6 ;-) It says that the last firmware update was done today (15.01) Can it affect the ability to run dorita script?

**Comment by koalazak** [comment]
dorita980 works with 1.6.6.
Check your robot ip.

**Comment by tomto147** [comment]
OK I will give it a try. What voice commands activated by Siri are actually available?

**Comment by tomto147** [comment]
OK I was able to extract the information using dorita. But... I can not get it to work... When turning Roomba on nothing happens. When pressing off to whole homebridge stops working with the following errors

[1/15/2017, 6:59:06 PM] [Roomba] Roomba Start!
[1/15/2017, 6:59:07 PM] [Roomba] Roomba is Ruuuuuuuuuuning!
[1/15/2017, 7:01:31 PM] [Roomba] Roomba Pause & Dock!
[1/15/2017, 7:01:32 PM] [Roomba] Roomba is Pause!
[1/15/2017, 7:01:35 PM] [Roomba] Roomba Checking the Status!
[1/15/2017, 7:01:36 PM] [Roomba] Roomba Get Status!
/usr/local/lib/node_modules/homebridge-roomba/index.js:81
                                    var status = JSON.parse(body.robot_status);
                                                                ^

TypeError: Cannot read property 'robot_status' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/index.js:81:65)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by tomto147** [comment]
I got it to work but with this version https://github.com/steedferns/homebridge-roomba980
