### ISSUE TITLE
Roomba 960 doesn't start

### ISSUE THREAD

**Issue by andijegg** [umesan/homebridge-roomba#10]
Hi,

I installed the Plugin, and get the robotpwd etc via dorita980 because of the Module in the Plugin don't work for me.

Homebridge is starting correctly with the roomba plugin and the Button showed in the Home App and I can push it. Homebridge shows that the roomba is startet, an by pushing a second time, that the roomba paused an dock, but in real nothing happens. Any Idea

Here are the starting Period of Homebridge and the log from starting and ending via the home App

```
[2017-10-10 16:34:06] Loaded plugin: homebridge-chamberlain
[2017-10-10 16:34:06] Registering accessory 'homebridge-chamberlain.Chamberlain'
[2017-10-10 16:34:06] ---
[2017-10-10 16:34:06] Loaded plugin: homebridge-delay-switch
[2017-10-10 16:34:06] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2017-10-10 16:34:06] ---
[2017-10-10 16:34:07] Loaded plugin: homebridge-harmonyhub
[2017-10-10 16:34:07] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2017-10-10 16:34:07] ---
[2017-10-10 16:34:08] Loaded plugin: homebridge-neato
[2017-10-10 16:34:08] Registering platform 'homebridge-neato.NeatoVacuumRobot'
[2017-10-10 16:34:08] ---
[2017-10-10 16:34:11] Loaded plugin: homebridge-roomba
[2017-10-10 16:34:11] Registering accessory 'homebridge-roomba.Roomba'
[2017-10-10 16:34:11] ---
[2017-10-10 16:34:12] Loaded plugin: homebridge-sonos
[2017-10-10 16:34:12] Registering accessory 'homebridge-sonos.Sonos'
[2017-10-10 16:34:12] ---
[2017-10-10 16:34:13] Loaded plugin: homebridge-vera
VeraLink initializing
[2017-10-10 16:34:13] Registering platform 'homebridge-veralink.Vera'
[2017-10-10 16:34:13] ---
[2017-10-10 16:34:13] Loaded config.json with 10 accessories and 4 platforms.
[2017-10-10 16:34:13] ---
[2017-10-10 16:34:13] Loading 4 platforms...
[2017-10-10 16:34:13] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[2017-10-10 16:34:13] [HarmonyHub Wohnzimmer] Initializing HarmonyHub platform...
Using Logitech Harmony hub ip address from configuration
[2017-10-10 16:34:13] [HarmonyHub Wohnzimmer] Connecting to Logitech Harmony remote hub...
[2017-10-10 16:34:13] [HarmonyHub Schlafzimmer] Initializing HarmonyHub platform...
Using Logitech Harmony hub ip address from configuration
[2017-10-10 16:34:13] [HarmonyHub Schlafzimmer] Connecting to Logitech Harmony remote hub...
[2017-10-10 16:34:13] [Vera] Initializing Vera platform...
[2017-10-10 16:34:13] Loading 10 accessories...
[2017-10-10 16:34:13] [Garagentor] Initializing Chamberlain accessory...
[2017-10-10 16:34:13] [Lisi] Initializing Roomba accessory...
[2017-10-10 16:34:13] [Lautsprecher Küche] Initializing Sonos accessory...
[2017-10-10 16:34:13] [Lautsprecher Esszimmer] Initializing Sonos accessory...
[2017-10-10 16:34:13] [Lautsprecher Dusche] Initializing Sonos accessory...
[2017-10-10 16:34:13] [Lautsprecher Bad] Initializing Sonos accessory...
[2017-10-10 16:34:13] [Delay 5min] Initializing DelaySwitch accessory...
[2017-10-10 16:34:13] [Delay 3min] Initializing DelaySwitch accessory...
[2017-10-10 16:34:13] [Delay Türe 30sek] Initializing DelaySwitch accessory...
[2017-10-10 16:34:13] [Delay Garage 30sek] Initializing DelaySwitch accessory...
Process Device 43: Haustüre
Process Device 3: Türschlüssel funktioniert nicht
[2017-10-10 16:34:14] [Vera] Initializing platform accessory 'Haustüre'...
[2017-10-10 16:34:14] [Vera] Initializing platform accessory 'Türschlüssel funktioniert nicht'...
[2017-10-10 16:34:14] [Lautsprecher Küche] Found a playable coordinator device at 192.168.178.22 in zone 'Küche' for accessory 'Lautsprecher Küche' in accessory room 'Küche'
[2017-10-10 16:34:15] [HarmonyHub Wohnzimmer] Connected to Logitech Harmony remote hub
[2017-10-10 16:34:15] [HarmonyHub Wohnzimmer] Fetching Logitech Harmony devices and activites...
[2017-10-10 16:34:15] [HarmonyHub Wohnzimmer] Fetching Logitech Harmony activities...
[2017-10-10 16:34:15] [Lautsprecher Esszimmer] Found a playable coordinator device at 192.168.178.22 in zone 'Küche' for accessory 'Lautsprecher Esszimmer' in accessory room 'Esszimmer'
[2017-10-10 16:34:15] [HarmonyHub Schlafzimmer] Connected to Logitech Harmony remote hub
[2017-10-10 16:34:15] [HarmonyHub Schlafzimmer] Fetching Logitech Harmony devices and activites...
[2017-10-10 16:34:15] [HarmonyHub Schlafzimmer] Fetching Logitech Harmony activities...
[2017-10-10 16:34:15] [Lautsprecher Dusche] Found a playable coordinator device at 192.168.178.55 in zone 'Dusche' for accessory 'Lautsprecher Dusche' in accessory room 'Dusche'
[2017-10-10 16:34:16] [Lautsprecher Bad] Found a playable coordinator device at 192.168.178.58 in zone 'Bad' for accessory 'Lautsprecher Bad' in accessory room 'Bad'
[2017-10-10 16:34:16] [HarmonyHub Wohnzimmer] Found activities: 
	Kino
	PowerOff
	Fernsehen
	Radio
[2017-10-10 16:34:16] [HarmonyHub Schlafzimmer] Found activities: 
	TV
	Fernsehen normal
	PowerOff
	Apple TV
[2017-10-10 16:34:16] [HarmonyHub Wohnzimmer] Initializing platform accessory 'Fernsehen'...
[2017-10-10 16:34:16] [HarmonyHub Wohnzimmer] Initializing platform accessory 'Kino'...
[2017-10-10 16:34:16] [HarmonyHub Wohnzimmer] Initializing platform accessory 'Radio'...
[2017-10-10 16:34:16] [HarmonyHub Schlafzimmer] Initializing platform accessory 'Apple TV'...
[2017-10-10 16:34:16] [HarmonyHub Schlafzimmer] Initializing platform accessory 'Fernsehen normal'...
[2017-10-10 16:34:16] [HarmonyHub Schlafzimmer] Initializing platform accessory 'TV'...
[2017-10-10 16:34:17] [NeatoVacuumRobot] Found robot #1: Hugo
[2017-10-10 16:34:17] [NeatoVacuumRobot] Initializing platform accessory 'Hugo'...
```

```
[2017-10-10 16:34:17] Homebridge is running on port 42531.
[2017-10-10 16:41:49] [Lisi] Roomba Start!
[2017-10-10 16:41:51] [Lisi] Roomba Connect!
[2017-10-10 16:41:51] [Lisi] Roomba is Ruuuuuuuuuunning!
[2017-10-10 16:42:08] [Lisi] Roomba Pause & Dock!
[2017-10-10 16:42:10] [Lisi] Roomba Connect!
[2017-10-10 16:42:10] [Lisi] Roomba is Pauuuuuuuuuuse!
[2017-10-10 16:42:15] [Lisi] Checking the Status of Roomba!
[2017-10-10 16:42:15] [Lisi] Get Status of Roomba!
[2017-10-10 16:42:15] [Lisi] { cleanMissionStatus: 
   { cycle: 'none',
     phase: 'charge',
     expireM: 0,
     rechrgM: 0,
     error: 0,
     notReady: 0,
     mssnM: 0,
     sqft: 0,
     initiator: 'localApp',
     nMssn: 0 },
  pose: { theta: 0, point: { x: 0, y: 0 } },
  bin: { present: true, full: false },
  batPct: 100 }
[2017-10-10 16:42:15] [Lisi] Roomba is not Running....You Please Help.
```

When I try to get the robotpwd etc whiten the App whit this command 

`pi@homebridge:/usr/local/lib/node_modules/homebridge-roomba $ npm run getrobotpwd 192.16.xx.xx`

the tool runs and I get this line Back when I Press any Button

```
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
undefined
```

And after a while this error appears 

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.16.178.53:8883
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-roomba@1.0.0 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.16.178.53"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-roomba@1.0.0 getrobotpwd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-10-10T15_18_20_815Z-debug.log

```

Whit dorita980 I can read out the robotpwd etc.

**Comment by andijegg** [comment]
Now I can delimit the failure. 

The Robot starts correctly, so the Config is ok, but the robot only starts by pressing the button in the Home App for the second time (and after switching off before) and only when I open the iRobot App a few seconds after switching the Button in the Home App to ON.

Have anyone a Idea what can cause this behavior?

**Comment by umesan** [comment]
> Roomba 960 doesn't start

Some problems were solved in [v1.0.1](https://github.com/umesan/homebridge-roomba/releases/tag/v1.0.1)

>but the robot only starts by pressing the button in the Home App for a second time (and after switching off before) and only when I open the iRobot App a few seconds after switching the Button in the Home App to ON.

I do not understand.
I would like you to explain the problem and circumstances in detail.

**Comment by andijegg** [comment]
Hi,

I will test the Version 1.0.1

The Roomba ist recognized by the Plugin and it is shown correctly in the home App and it works, but moste of the Time it works not until I give the start command a second time via the home App.

For example, I press the button in the home app and nothing happens. So I switch the button of and activate it a second time and the Roomba starts.

A other way to get it run is, to start the Roomba via the home App and when nothing happens I have to open the roomba App, when I do this, the Roomba starts working, without pressing any button in the Roomba App.

I hope, the explanation is good enough, my english is not the best... :-)
