### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by Krillle** [umesan/homebridge-roomba#13]
Starting homebridge I still get the message mentions in #9 :

ERROR LOADING PLUGIN homebridge-roomba:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:134:14)
at Array.forEach (native)

My system is Node version v4.8.4

Any ideas? Regards, Christian

**Comment by iRayanKhan** [comment]
Node V4? Node goes to Node V11 now try that
