### ISSUE TITLE
Homebridge can not load Roomba Plugin

### ISSUE THREAD

**Issue by Kfortune117** [umesan/homebridge-roomba#18]
Hopefully somebody is still watching these...

When I try to start homebridge, I keep getting this error. I am trying to connect a Roomba I7. Not sure if this plugin will work but I would think that I would get past this point whether it works or not.

[2019-2-10 11:39:59] Loaded config.json with 0 accessories and 3 platforms.
[2019-2-10 11:39:59] ---
[2019-2-10 11:40:00] Loaded plugin: homebridge-arlo
[2019-2-10 11:40:00] Registering platform 'homebridge-arlo.Arlo'
[2019-2-10 11:40:00] ---
[2019-2-10 11:40:01] Loaded plugin: homebridge-camera-ffmpeg
[2019-2-10 11:40:01] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpe                                                                                                                                                             g'
[2019-2-10 11:40:01] ---
[2019-2-10 11:40:02] Loaded plugin: homebridge-roomba
[2019-2-10 11:40:02] Registering accessory 'homebridge-roomba.Roomba'
[2019-2-10 11:40:02] ---
[2019-2-10 11:40:02] Loading 3 platforms...
[2019-2-10 11:40:02] [Arlo] Initializing Arlo platform...
[2019-2-10 11:40:02] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered                                                                                                                                                              by any plugin.");
      ^

Error: The requested platform 'Roomba' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.                                                                                                                                                             js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge                                                                                                                                                             :17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Config.Json:

{
	"bridge":
		{
		"name": "Homebridge",
		"username": "redacted but correct",
		"port": 51826,
		"pin": "031-32-154"
		},
	"platforms":
	 [
		{
			"platform": "Arlo",
			"name": "Arlo",
			"email": "redacted but correct",
			"password": "redacted but correct",
			"interval": 6000,
			"streaming":
			{
				"videoDecoder": "h264_mmal",
				"videoEncoder": "h264_omx",
				"packetSize": 564
			} 
		},
			{
			"platform": "Camera-ffmpeg",
			"cameras": 
			[
				{
					"name": "Front Door Camera",
					"videoConfig": 
					{
						"source": "arlo",
						"maxStreams": 2,
						"maxWidth":1920 ,
						"maxHeight":1080 ,
						"maxFPS": 30,
						"maxBitrate": 300,
						"vcodec": "copy",
						"audio": false,
						"debug": true,
						"arloUserName": "redacted but correct",
						"arloPassword": "redacted but correct",
						"arloCameraIndex": "0"
					}
				},
				{
					"name": "Sliding Door Camera",
					"videoConfig": 
					{
						"source": "arlo",
						"maxStreams": 2,
						"maxWidth":1920 ,
						"maxHeight":1080 ,
						"maxFPS": 30,
						"maxBitrate": 300,
						"vcodec": "copy",
						"audio": false,
						"debug": true,
						"arloUserName": "redacted but correct",
						"arloPassword": "redacted but correct",
						"arloCameraIndex": "1"
					}
				}
			]
		},
		{
			"platform": "Roomba",
			"name": "Roomba",
			"robots":
			[
				{
					"name": "Roomba",
					"blid": "redacted but correct",
					"password": "redacted but correct",
					"address": "10.0.1.34"
				}
			]
		}
	]
}

**Comment by Mx-Razvan** [comment]
Add it as accesory not as platform. It works with i7+
"accessories": [
  {
    "accessory": "Roomba",
    "name": "Roomba",
    "blid":"0123456789abcdef",
    "robotpwd":":1:2345678910:ABCDEFGHIJKLMNOP",
    "ipaddress": "192.168.xx.xx"
  }
]

**Comment by francen** [comment]
my Roomba S9+ is showing in HomeKit via homebridge and as an accessory (defining it under Platform wouldn't work), however, when the vacuum is ON, it still shows as OFF in HomeKit ... I had no problem getting the password and the BLID ...

just an update/claificaiton to the above description ... HomeKit DOES allow me to turn the Roomba S9+ on/off ... it just never *senses* that if I turn the device on via iRobot's app, that it is indeed running (HomeKit says "OFF" while it is running) ...
