### ISSUE TITLE
Works with Roomba i7

### ISSUE THREAD

**Issue by takamasa-arch** [umesan/homebridge-roomba#19]
This is just information for who want to know your roomba can works with this plugin.

Maybe it may be works below as well since SDK which this plugin used is supported following types of roomba. (i7/i7+, 980, 960, e5, 690, 675, etc)

**Comment by kabrider** [comment]
How must i do with the I7 to get password I follow the command but I have this error 
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
undefined
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 192.168.1.18:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.18',
  port: 8883
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dorita980@3.1.7 getpassword: `node ./bin/getpassword.js "192.168.1.18"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dorita980@3.1.7 getpassword script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-12T14_30_30_872Z-debug.log
