### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yannip1234** [umesan/homebridge-roomba#2]
Hi, I'm getting this crash. Can you help?

`[6/14/2016, 3:04:16 AM] [Roomba] Roomba Start!
[6/14/2016, 3:04:16 AM] [Roomba] Roomba is Ruuuuuuuuuuning!
[6/14/2016, 3:04:16 AM] [Roomba] Roomba Pause & Dock!
[6/14/2016, 3:04:17 AM] [Roomba] Roomba is Pause!
[6/14/2016, 3:04:20 AM] [Roomba] Roomba Checking the Status!
[6/14/2016, 3:04:21 AM] [Roomba] Roomba Get Status!
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/index.js:81:55)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-roomba/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)`

**Comment by umesan** [comment]
Thank you very much.
I upgraded it, so I will close this.
