### ISSUE TITLE
Error while getting password

### ISSUE THREAD

**Issue by ilyabreev** [umesan/homebridge-roomba#20]
```
pi@raspberrypi:/usr/lib/node_modules/homebridge-roomba $ sudo npm run getrobotpwd 192.168.2.50

> homebridge-roomba@1.0.1 getrobotpwd /usr/lib/node_modules/homebridge-roomba
> cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.2.50"

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.8.0 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

audited 1166 packages in 10.471s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
<valid robot data here>
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: 1995864528:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2159:

Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-roomba@1.0.1 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.2.50"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge-roomba@1.0.1 getrobotpwd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-20T11_45_22_460Z-debug.log
```

**Comment by julien235** [comment]
Hi, 

I think you do not search the answer anymore, but for the others people.

Add a custom openssl config before call node bin.

OPENSSL_CONF=openssl.cnf node ./bin/getpassword.js "192.168.2.50"

openssl.cnf :
```
openssl_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = ssl_default_sect

[ssl_default_sect]

Options = UnsafeLegacyRenegotiation
```
