### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JimBobSD** [umesan/homebridge-roomba#3]
I absolutely love the Roomba plugin.  I've combined it with the homebridge-people plugin so that Roomba runs only when no one is home.  When someone arrives home, it tells Roomba to pause and dock.  Absolutely fantastic!

But I've been having this crash, which crashes Homebridge completely.  This occurs when Homebridge sends the command for Roomba to turn off.  Roomba may or not be running at this time.

[10/10/2016, 11:43:30 AM] [Roomba] Roomba Pause & Dock!
[10/10/2016, 11:43:31 AM] [Roomba] Roomba is Pause!
[10/10/2016, 11:43:34 AM] [Roomba] Roomba Checking the Status!
[10/10/2016, 11:43:34 AM] [Roomba] Roomba Get Status!
C:\Users\UserName\AppData\Roaming\npm\node_modules\homebridge-roomba\index.js:8
1
                                    var status = JSON.parse(body.robot_status);
                                                                ^

TypeError: Cannot read property 'robot_status' of undefined
    at Object.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\h
omebridge-roomba\index.js:81:65)
    at Request.self.callback (C:\Users\UserName\AppData\Roaming\npm\node_module
s\homebridge-roomba\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\
homebridge-roomba\node_modules\request\request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_
modules\homebridge-roomba\node_modules\request\request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by JimBobSD** [comment]
Update for anyone having a similar problem.  I uninstalled the plugin and installed Roomba980 from:

https://www.npmjs.com/package/homebridge-roomba980

I also installed dorita980, which is required for the roomba980 plugin.  I also updated my config.json file to reflect the different settings for the Roomba980 plugin.

Everything is working great now.  No issues after a couple days.

**Comment by umesan** [comment]
Thank you very much.
I upgraded it, so I will close this.
