### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by Mx-Razvan** [umesan/homebridge-roomba#8]
[5/7/2017, 2:59:38 PM] ====================
[5/7/2017, 2:59:38 PM] ERROR LOADING PLUGIN homebridge-roomba:
[5/7/2017, 2:59:38 PM] Error: Plugin /usr/lib/node_modules/homebridge-roomba does not contain the 'homebridge' package in 'engines'.
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:49:11)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
[5/7/2017, 2:59:38 PM] ====================

Any idea?

**Comment by umesan** [comment]
When does the error occur at what timing?

**Comment by Mx-Razvan** [comment]
At the homebridge startup. It doesn't run at all

**Comment by ifongie** [comment]
i have similar issue when Homebridge starts:

[37m[5/8/2017, 2:33:02 PM][39m [1m[31mERROR LOADING PLUGIN homebridge-roomba:[39m[22m
stdout
14:33:02
[37m[5/8/2017, 2:33:02 PM][39m [1m[31mError: Plugin /usr/local/lib/node_modules/homebridge-roomba does not contain the 'homebridge' package in 'engines'.
stdout
14:33:02
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:49:11)
stdout
14:33:02
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
stdout
14:33:02
    at Array.forEach (native)
stdout
14:33:02
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
stdout
14:33:02
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
stdout
14:33:02
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
stdout
14:33:02
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
stdout
14:33:02
    at Module._compile (module.js:571:32)
stdout
14:33:02
    at Object.Module._extensions..js (module.js:580:10)
stdout
14:33:02
    at Module.load (module.js:488:32)[39m[22m

**Comment by brn2prgrm** [comment]
Similar startup error here:
22:09:47 - ====================
22:09:47 - ERROR LOADING PLUGIN homebridge-roomba:
22:09:47 - Error: Plugin /Users/mikeds/.npm-packages/lib/node_modules/homebridge-roomba does not contain the 'homebridge' package in 'engines'.
    at Plugin.load (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/lib/plugin.js:49:11)
    at Server.<anonymous> (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/Users/mikeds/.npm-packages/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

I'm using JSON Node v8.0.0 right now and I only have problems with this project.  In fact, using the Roomba890 project yields no errors, but it is older code.  I will be using that for the time being.  Let me know how I can help troubleshoot!

**Comment by amitgandhinz** [comment]
I'm getting the same error as above.  Im running on a RPi.  I'll see how i go with the Roomba980 project.

**Comment by amitgandhinz** [comment]
looking at other home bridge plugins, i believe you need to add the following to the `package.json` file:

```
"engines": {
    "node": ">=0.12.0",
    "homebridge": ">=0.2.0"
  }
```

**Comment by jchristman** [comment]
Any chance you could push this change to the npm repository? I'm getting this error also. Thanks!

**Comment by iRonin** [comment]
Could we have this one in?

**Comment by umesan** [comment]
Thank you.
- Merged https://github.com/umesan/homebridge-roomba/pull/9 pull request.
- [I updated npm](https://www.npmjs.com/package/homebridge-roomba).
